In [1]:
import pandas as pd 
df = pd.read_csv("C:\\Users\\Ashok Rawat\\Downloads\\mountrip_adventures_data.csv")

In [2]:
df.head()

,name,phone,platform,package,travel_date,amount,nights,num_people,stay_type
0,Vijaypal Chopra,9371064926,Instagram,Tungnath,05-05-2025,7500.0,3,1,Hotel
1,Nikhil Gupta,9540498739,Direct,Tungnath,05-05-2025,6000.0,2,1,Hotel
2,Ramesh Bhatt,9847223359,Direct,Badrinath,05-05-2025,16000.0,1,4,Hotel
3,Arjun Rawal,9161701150,Direct,Deoriatal,06-05-2025,5500.0,3,1,Hotel
4,Arjun Malhotra,9229924490,Instagram,Badrinath,07-05-2025,40000.0,3,5,Hotel

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 760 entries, 0 to 759
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         760 non-null    object
 1   phone        760 non-null    int64
 2   platform     760 non-null    object
 3   package      760 non-null    object
 4   travel_date  760 non-null    object
 5   amount       753 non-null    float64
 6   nights       760 non-null    int64
 7   num_people   760 non-null    int64
 8   stay_type    760 non-null    object
dtypes: float64(1), int64(3), object(5)
memory usage: 53.6+ KB

In [4]:
df.describe(include = 'all')

,name,phone,platform,package,travel_date,amount,nights,num_people,stay_type
count,760,7.600000e+02,760,760,760,753.000000,760.000000,760.000000,760
unique,760,NaN,4,8,237,NaN,NaN,NaN,2
top,Varun Dwivedi,NaN,Instagram,Kedarnath,21-07-2025,NaN,NaN,NaN,Camp
freq,1,NaN,250,546,11,NaN,NaN,NaN,546
mean,NaN,9.561231e+09,NaN,NaN,NaN,13700.531208,2.050000,1.917105,NaN
std,NaN,2.624394e+08,NaN,NaN,NaN,10982.980050,1.034389,1.371543,NaN
min,NaN,9.100620e+09,NaN,NaN,NaN,4000.000000,1.000000,1.000000,NaN
25%,NaN,9.331060e+09,NaN,NaN,NaN,5500.000000,1.000000,1.000000,NaN
50%,NaN,9.577989e+09,NaN,NaN,NaN,9000.000000,2.000000,1.000000,NaN
75%,NaN,9.790409e+09,NaN,NaN,NaN,18000.000000,3.000000,3.000000,NaN
max,NaN,9.999206e+09,NaN,NaN,NaN,65000.000000,5.000000,5.000000,NaN

In [5]:
df.shape

(760, 9)

In [6]:
df.isnull().sum()

name           0
phone          0
platform       0
package        0
travel_date    0
amount         7
nights         0
num_people     0
stay_type      0
dtype: int64

In [7]:
df["amount"] = df["amount"].fillna(df["num_people"] * df.groupby(["package","nights"])["amount"].transform(lambda x: (x / df.loc[x.index, "num_people"]).median()))

In [8]:
df.isnull().sum()

name           0
phone          0
platform       0
package        0
travel_date    0
amount         0
nights         0
num_people     0
stay_type      0
dtype: int64

In [10]:
df

,name,phone,platform,package,travel_date,amount,nights,num_people,stay_type
0,Vijaypal Chopra,9371064926,Instagram,Tungnath,05-05-2025,7500.0,3,1,Hotel
1,Nikhil Gupta,9540498739,Direct,Tungnath,05-05-2025,6000.0,2,1,Hotel
2,Ramesh Bhatt,9847223359,Direct,Badrinath,05-05-2025,16000.0,1,4,Hotel
3,Arjun Rawal,9161701150,Direct,Deoriatal,06-05-2025,5500.0,3,1,Hotel
4,Arjun Malhotra,9229924490,Instagram,Badrinath,07-05-2025,40000.0,3,5,Hotel
...,...,...,...,...,...,...,...,...,...
755,subhash Singh,9726717933,Direct,Tungnath,25-02-2026,7500.0,3,1,Hotel
756,Nikhil Chauhan,9608651543,Direct,Badrinath,26-02-2026,8000.0,3,1,Hotel
757,Sneha Gupta,9391359421,Direct,Chopta,26-02-2026,4000.0,1,1,Hotel
758,Dipendra Srivastava,9575649405,Direct,Rudranath,28-02-2026,9000.0,3,1,Hotel
759,Varun Dwivedi,9272233159,Instagram,Deoriatal,28-02-2026,9100.0,2,2,Hotel

In [17]:
#finding per person amount

df["amount_per_person"] = df["amount"] / df["num_people"]

In [16]:
df

,name,phone,platform,package,travel_date,amount,nights,num_people,stay_type,amount_per_person
0,Vijaypal Chopra,9371064926,Instagram,Tungnath,05-05-2025,7500.0,3,1,Hotel,7500.0
1,Nikhil Gupta,9540498739,Direct,Tungnath,05-05-2025,6000.0,2,1,Hotel,6000.0
2,Ramesh Bhatt,9847223359,Direct,Badrinath,05-05-2025,16000.0,1,4,Hotel,4000.0
3,Arjun Rawal,9161701150,Direct,Deoriatal,06-05-2025,5500.0,3,1,Hotel,5500.0
4,Arjun Malhotra,9229924490,Instagram,Badrinath,07-05-2025,40000.0,3,5,Hotel,8000.0
...,...,...,...,...,...,...,...,...,...,...
755,subhash Singh,9726717933,Direct,Tungnath,25-02-2026,7500.0,3,1,Hotel,7500.0
756,Nikhil Chauhan,9608651543,Direct,Badrinath,26-02-2026,8000.0,3,1,Hotel,8000.0
757,Sneha Gupta,9391359421,Direct,Chopta,26-02-2026,4000.0,1,1,Hotel,4000.0
758,Dipendra Srivastava,9575649405,Direct,Rudranath,28-02-2026,9000.0,3,1,Hotel,9000.0
759,Varun Dwivedi,9272233159,Instagram,Deoriatal,28-02-2026,9100.0,2,2,Hotel,4550.0

In [18]:
pip install pymysql sqlalchemy

Collecting pymysqlNote: you may need to restart the kernel to use updated packages.

  Downloading pymysql-1.1.2-py3-none-any.whl.metadata (4.3 kB)
Collecting sqlalchemy
  Downloading sqlalchemy-2.0.48-cp312-cp312-win_amd64.whl.metadata (9.8 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.3.2-cp312-cp312-win_amd64.whl.metadata (3.8 kB)
Collecting typing-extensions>=4.6.0 (from sqlalchemy)
  Downloading typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Downloading pymysql-1.1.2-py3-none-any.whl (45 kB)
Downloading sqlalchemy-2.0.48-cp312-cp312-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---------------------------------- ----- 1.8/2.1 MB 7.2 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 7.1 MB/s eta 0:00:00
Downloading greenlet-3.3.2-cp312-cp312-win_amd64.whl (231 kB)
Downloading typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Installing collected packages: typing-extensions, pymysql, greenlet, sqlalchemy

   ---------- ----------------------------- 1/4 [pymysql]
   -------------------- ------------------- 2/4 [greenlet]
   -------------------- ------------------- 2/4 [greenlet]
   -------------------- ------------------- 2/4 [greenlet]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ---------------------------------------- 4/4 [sqlalchemy]

Successfully installed greenlet-3.3.2 pymysql-1.1.2 sqlalchemy-2.0.48 typing-extensions-4.15.0

In [21]:
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

url = URL.create(
    drivername="mysql+pymysql",
    username="root",
    password="ashok@1234", 
    host="localhost",
    port=3306,
    database="mountrip_adventures"
)

engine = create_engine(url)

print("✅ Connected successfully")

✅ Connected successfully

In [22]:
# pushing data to mysql 

df.to_sql(
    name="raw_data",
    con=engine,
    if_exists="replace",  
    index=False
)

print("✅ Data successfully loaded into MySQL table: raw_data")

✅ Data successfully loaded into MySQL table: raw_data

In [23]:
#verifiying data

test_df = pd.read_sql("SELECT * FROM raw_data LIMIT 5;", engine)
print(test_df)

              name       phone   platform    package travel_date   amount  \
0  Vijaypal Chopra  9371064926  Instagram   Tungnath  05-05-2025   7500.0
1     Nikhil Gupta  9540498739     Direct   Tungnath  05-05-2025   6000.0
2     Ramesh Bhatt  9847223359     Direct  Badrinath  05-05-2025  16000.0
3      Arjun Rawal  9161701150     Direct  Deoriatal  06-05-2025   5500.0
4   Arjun Malhotra  9229924490  Instagram  Badrinath  07-05-2025  40000.0

   nights  num_people stay_type  amount_per_person
0       3           1     Hotel             7500.0
1       2           1     Hotel             6000.0
2       1           4     Hotel             4000.0
3       3           1     Hotel             5500.0
4       3           5     Hotel             8000.0

In [25]:
#fixing the data types

df["travel_date"] = pd.to_datetime(df["travel_date"], dayfirst=True, errors="coerce")
df["amount"] = df["amount"].astype(int)
df["num_people"] = df["num_people"].astype(int)
df["nights"] = df["nights"].astype(int)